Vagrant.configure("2") do |config|

    config.vm.box = "generic/alpine319"
    config.vm.define "pbureeraS" do |server|

        server.vm.hostname = "pbureeraS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
        server.vm.provider "virtualbox" do |vm|
            vm.name = "pbureeraS"
            vm.memory = "2048"
            vm.cpus = "1"
        end
        server.vm.provision "shell", path: "scripts/setupServer.sh"

    end

end
