# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mofikrat <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/30 13:59:53 by mofikrat          #+#    #+#              #
#    Updated: 2019/07/30 19:33:11 by mofikrat         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM ubuntu:latest

MAINTAINER mofikrat <mofikrat@student.42.fr>

RUN apt update && apt upgrade
RUN apt-get install -y  git build-essential manpages-dev man-db vim

RUN echo "echo \"#CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC#\"" >> ~/.bashrc &&\
	echo "echo \"WELCOME TO YOUR C CONTAINER\"" >> ~/.bashrc &&\
	echo "echo \"ENJOY CODING!!!\"" >> ~/.bashrc &&\
	echo "echo \"#CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC#\"" >> ~/.bashrc &&\
	echo "echo \"        \\---------\\      \"" >> ~/.bashrc &&\
	echo "echo \"        /  __    __\\        \"" >> ~/.bashrc &&\
	echo "echo \"       /_/# \\__/# \\        \"" >> ~/.bashrc &&\
	echo "echo \"    (.   \\__/  \\__/        \"" >> ~/.bashrc &&\
	echo "echo \"      )       _,  |          \"" >> ~/.bashrc &&\
	echo "echo \" _____/\\     _   /          \"" >> ~/.bashrc &&\
	echo "echo \"     \\  \._____,/           \"" >> ~/.bashrc &&\
	echo "echo \"     ..__)\\  /(_\           \"" >> ~/.bashrc &&\
	echo "echo \"        \\) \\/  ( \                     \"" >> ~/.bashrc &&\
	echo "echo \"           |      \\\    by mofikrat  \"" >> ~/.bashrc &&\
	echo "echo \"#CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC#\"" >> ~/.bashrc
