Vagrant.configure("2") do |config|
# 2 is the latest version of the object config that will be used for configuration
    config.vm.define "pbureeraS" do |server|
        server.vm.box = "generic/alpine319"
        server.vm.hostname = "pbureeraS"
        server.vm.network "private_network", ip: "192.168.56.110"
        # synced folder is used to share files between the host and the guest
        server.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
        server.vm.provider "virtualbox" do |vm|
            vm.name = "pbureeraS"
            vm.memory = "1024"
            vm.cpus = "1"
        end
        server.vm.provision "shell", path: "scripts/setupServer.sh"
    end
     
    config.vm.define "pbureeraSW" do |worker|
        worker.vm.box = "generic/alpine319"
        worker.vm.hostname = "pbureeraSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
        worker.vm.provider "virtualbox" do |vm|
            vm.name = "pbureeraSW"
            vm.memory = "1024"
            vm.cpus = "1"
        end
        worker.vm.provision "shell", path: "scripts/setupWorker.sh"
    end
  
end
